### ISSUE TITLE
New Cases 7-7

### ISSUE THREAD

**Issue by lgfelton** [slu-openGIS/covid_daily_viz#2]
Want to confirm there were no new cases reported for any zipcode in St. Louis County on 7-7-2021. There were 97 cases reported on 7-6.

**Comment by chris-prener** [comment]
hi @lgfelton - Thanks for reaching out! The data show no change because both the City and the County's ESRI servers were down last night. Hoping they'll be back up tonight and will show change. FWIW the ZIP code data are pretty imperfect measures of day-to-day change. That's why I report 14-day averages for them.

**Comment by lgfelton** [comment]
Christopher,Thanks for the reply. I appreciate the work you have put into this site.LarrySent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Christopher Prener ***@***.***> Date: 7/8/21  2:10 PM  (GMT-06:00) To: slu-openGIS/covid_daily_viz ***@***.***> Cc: lgfelton ***@***.***>, Mention ***@***.***> Subject: Re: [slu-openGIS/covid_daily_viz] New Cases 7-7 (#2) 
hi @lgfelton - Thanks for reaching out! The data show no change because both the City and the County's ESRI servers were down last night. Hoping they'll be back up tonight and will show change. FWIW the ZIP code data are pretty imperfect measures of day-to-day change. That's why I report 14-day averages for them.

**Comment by chris-prener** [comment]
My pleasure!
